version: "3.8"

x-wait: &wait
  WAIT_HOSTS: "${DB_HOST:-database}:${DB_PORT:-5432}"
  WAIT_BEFOR: 0
  WAIT_SLEEP_INTERVAL: 5
  WAIT_TIMEOUT: 5

services:
  database:
    image: "postgres:13.4"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-foundrymetamanager}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
  api:
    build:
      dockerfile: backend.Dockerfile
      context: .
    restart: on-failure
    command: "sh -c '/wait && uvicorn main:app --reload --host 0.0.0.0 --port 8000'"
    volumes:
      - ./backend:/home/fmm/app
    environment:
      <<: *wait
    ports:
      - "8000:8000"
